### ISSUE TITLE
求编译32的，我编译后无法引导，求大神编译32 64的吧

### ISSUE THREAD

**Issue by lozn00** [beatfan/UEFI_grub2#1]
因为要加载iso文件，需要一个linux16命令，不得不编译32的

**Comment by beatfan** [comment]
抱歉，最近比较忙，没有怎么查看，我这个版本可以引导iso文件的，我一直用它来引导安装Centos、Ubuntu、Debian等，详细参考博客：http://blog.csdn.net/u010875635/article/details/74289971

**Comment by lozn00** [comment]
我已经搞定了。。
