### ISSUE TITLE
建议参考下 AIO-Boot

### ISSUE THREAD

**Issue by OiCkilL** [beatfan/UEFI_grub2#3]
建议参考下 [AIO-Boot](https://github.com/nguyentumine/AIO-Boot) 这个项目。
实现方法更为科学

**Comment by beatfan** [comment]
也可以参考这个项目： [USB_Boot_With_Grub_Grub2_ISOLINUX](https://github.com/beatfan/USB_Boot_With_Grub_Grub2_ISOLINUX)
